apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: rvstore-order-api
        image: vergeops/k8s-rvstore-order-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - containerPort: 9002
        readinessProbe:
          httpGet:
            path: /orders
            port: 9002
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1