apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  labels:
    app: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: rvstore-product-api
        image: vergeops/k8s-rvstore-product-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /products/
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1